import Link from "next/link";
import getAllPosts from "../lib/getAllPosts";




//making the dynamic metadata//this function will run on the server side
export async function generateMetadata() {
    return {
        title: "All Posts",
        description: "Generated by create next app",
    };
    }


export default async function Postpage() {

    const posts = await getAllPosts();
    console.log(posts);
  return (
    <div>
    <div>All My Post Here</div>
    <ul>
        {
            posts.map((post)=><li key ={post.id}><Link href ={`/posts/${post.id}`}>{post.title}</Link></li>)
        }
        </ul>
        </div>
  )
}
