import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // whatever you go any page , the pages will be wrapped/ fired in this layout first 
  //and the in this layout it pass the pages content as children form here 
  // you can also use this layout to add global styles or components
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4 bg-orange-800 text-white font-medium">
          Home| About | Contact
        </nav>
        {children}
      </body>
    </html>
  );
}
